version: '3.8'
services:
  Telegram_2002db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=Telegram_2002
    ports:
      - '5434:5432'
    # expose:
    #   - 5432

  app:
    build:
      context: ../..
      dockerfile: docker/app/Dockerfile
    restart: always
    environment:
      - DB_HOST=Telegram_2002db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=12345678
      - DB_NAME=Telegram_2002
    ports:
      - '8080:8080'

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=truongloc@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=12345678
    ports:
      - '5050:80'


  redis-node-1:
    build:
      context: ../..
      dockerfile: docker/app/Dockerfile-node1
    ports:
      - '6123:6379'

  redis-node-2:
    build:
      context: ../..
      dockerfile: docker/app/Dockerfile-node2
    ports:
      - '6124:6379'

  redis-node-3:
    build:
      context: ../..
      dockerfile: docker/app/Dockerfile-node3
    ports:
      - '6125:6379'