version: '3.8'
services:
  Telegram_2002:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=Telegram_2002
      - POSTGRES_PASSWORD=12345678
    ports:
      - '5434:5432'
    expose:
      - 5432

  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_PORT=5432
      - DB_HOST=Telegram_2002
    ports:
      - '8080:8080'