version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=Telegram_2002
      - POSTGRES_PASSWORD=12345678
    ports:
      - '5433:5432'
